/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/*                                                                           */
/*                  This file is part of the program and library             */
/*         SCIP --- Solving Constraint Integer Programs                      */
/*                                                                           */
/*  Copyright (c) 2002-2023 Zuse Institute Berlin (ZIB)                      */
/*                                                                           */
/*  Licensed under the Apache License, Version 2.0 (the "License");          */
/*  you may not use this file except in compliance with the License.         */
/*  You may obtain a copy of the License at                                  */
/*                                                                           */
/*      http://www.apache.org/licenses/LICENSE-2.0                           */
/*                                                                           */
/*  Unless required by applicable law or agreed to in writing, software      */
/*  distributed under the License is distributed on an "AS IS" BASIS,        */
/*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. */
/*  See the License for the specific language governing permissions and      */
/*  limitations under the License.                                           */
/*                                                                           */
/*  You should have received a copy of the Apache-2.0 license                */
/*  along with SCIP; see the file LICENSE. If not visit scipopt.org.         */
/*                                                                           */
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/**@file        event_sepacuts.c
 * @ingroup     DEFPLUGINS_EVENT
 * @brief       eventhdlr for xyz event
 * @author      Chantal Reinartz Groba
 */

/*--+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9----+----0----+----1----+----2*/
#define SCIP_DEBUG
//#include "scip/tree.h"
#include <scip/pub_tree.h>
#include "event_sepacuts.h"
#include "type_mastercutdata.h"
#include "misc_varhistory.h"
#include "type_sepagcg.h"
#include "gcg.h"
#include "mastercutdata.h"
#include "pricer_gcg.h"
#include "scip/scip_mem.h"
#include "scip/struct_scip.h"
#include "struct_sepagcg.h"
#include "scip/struct_tree.h"

#define EVENTHDLR_NAME         "sepacuts"
#define EVENTHDLR_DESC         "event handler for keeping master cuts generated by a separator up-to-date"
#define STARTMAXCUTS            50

/*
 * Data structures
 */

/* TODO: fill in the necessary event handler data */

/** event handler data */
struct SCIP_EventhdlrData
{
   GCG_MASTERCUTDATA***       generatedcuts;          /**< arrays of newly generated separator cuts for each separator */
   GCG_STOREDCUT***           activecuts;             /**< arrays of active cuts */
   SCIP_HASHMAP*              rowxgeneratedidx;       /**< maps a row to its index in the generated array */
   SCIP_HASHMAP*              sepaxidx;               /**< maps a separator to its index in separator array */
   int*                       nactivecuts;            /**< number of active cuts */
   int*                       ngeneratecuts;          /**< number of newly generated cuts */
   int*                       activecutssize;         /**< size of memory allocated for active cuts */
   int*                       generatecutssize;       /**< size of memory allocated for generated cuts */
   int                        nsepas;                 /**< number of separators */
};
/*
 * Local methods
 */

/* put your local methods here, and declare them static */

SCIP_RETCODE createStoredCut(
   SCIP* scip,
   GCG_STOREDCUT** storedcut,
   GCG_MASTERCUTDATA* mastercutdata
   )
{
   assert(scip != NULL);
   assert(mastercutdata != NULL);
   assert(storedcut != NULL);
   assert(*storedcut != NULL);

   SCIP_CALL( SCIPallocBlockMemory(scip, storedcut) );
   (*storedcut)->mastercutdata = mastercutdata;
   (*storedcut)->knownvarhistory = NULL;
   SCIP_CALL( GCGvarhistoryCopyReference(scip, &((*storedcut)->knownvarhistory), GCGgetCurrentVarhistoryReference(scip)) );
   return SCIP_OKAY;
}

SCIP_RETCODE freeStoredCut(
   SCIP* scip,
   GCG_STOREDCUT** storedcut
   )
{
   assert(scip != NULL);
   assert(GCGisOriginal(scip));
   assert(storedcut != NULL);
   assert(*storedcut != NULL);

   SCIP_CALL( GCGvarhistoryFreeReference(scip, &((*storedcut)->knownvarhistory)) );
   GCGmastercutFree(scip, &((*storedcut)->mastercutdata));
   SCIPfreeBlockMemory(scip, storedcut);

   *storedcut = NULL;

   return SCIP_OKAY;
}


SCIP_RETCODE ensureGeneratedSize(
   SCIP* scip,
   SCIP_EVENTHDLRDATA* eventhdlrdata,
   int sepaidx,
   int size
)
{
   assert(scip != NULL);
   assert(eventhdlrdata != NULL);
   assert(eventhdlrdata->generatedcuts != NULL);
   assert(eventhdlrdata->generatedcuts[sepaidx] != NULL);
   assert(eventhdlrdata->ngeneratecuts[sepaidx] <= eventhdlrdata->generatecutssize[sepaidx]);
   assert(eventhdlrdata->ngeneratecuts[sepaidx] >= 0);

   if( eventhdlrdata->generatecutssize[sepaidx] < size )
   {
      int newmaxcuts = SCIPcalcMemGrowSize(scip, size);
      SCIP_CALL( SCIPreallocBlockMemoryArray(scip, &(eventhdlrdata->generatedcuts[sepaidx]), eventhdlrdata->generatecutssize[sepaidx], newmaxcuts) );
      eventhdlrdata->generatecutssize[sepaidx] = newmaxcuts;
   }

   assert(eventhdlrdata->generatecutssize[sepaidx] >= size);

   return SCIP_OKAY;
}


SCIP_RETCODE ensureActiveSize(
   SCIP* scip,
   SCIP_EVENTHDLRDATA* eventhdlrdata,
   int sepaidx,
   int size
)
{
   assert(scip != NULL);
   assert(eventhdlrdata != NULL);
   assert(eventhdlrdata->activecuts != NULL);
   assert(eventhdlrdata->activecuts[sepaidx] != NULL);
   assert(eventhdlrdata->nactivecuts[sepaidx] <= eventhdlrdata->activecutssize[sepaidx]);
   assert(eventhdlrdata->nactivecuts[sepaidx] >= 0);

   if( eventhdlrdata->activecutssize[sepaidx] < size )
   {
      int newmaxcuts = SCIPcalcMemGrowSize(scip, size);
      SCIP_CALL( SCIPreallocBlockMemoryArray(scip, &(eventhdlrdata->activecuts[sepaidx]), eventhdlrdata->activecutssize[sepaidx], newmaxcuts) );
      eventhdlrdata->activecutssize[sepaidx] = newmaxcuts;
   }

   assert(eventhdlrdata->activecutssize[sepaidx] >= size);

   return SCIP_OKAY;
}


SCIP_RETCODE addCutToGeneratedCutsSepa(
   SCIP* scip,
   GCG_MASTERCUTDATA* mastercutdata,
   int sepaidx
   )
{
   SCIP_EVENTHDLR* eventhdlr;
   SCIP_EVENTHDLRDATA* eventhdlrdata;
   SCIP_ROW* row;

   assert(scip != NULL);
   assert(GCGisMaster(scip));
   assert(mastercutdata != NULL);

   eventhdlr = SCIPfindEventhdlr(scip, EVENTHDLR_NAME);
   assert(eventhdlr != NULL);

   eventhdlrdata = SCIPeventhdlrGetData(eventhdlr);
   assert(eventhdlrdata != NULL);

   SCIP_CALL( GCGmastercutGetRow(mastercutdata, &row) );
   assert(row != NULL);

   SCIP_CALL( ensureGeneratedSize(scip, eventhdlrdata, sepaidx, eventhdlrdata->ngeneratecuts[sepaidx] + 1) );
   eventhdlrdata->generatedcuts[sepaidx][eventhdlrdata->ngeneratecuts[sepaidx]] = mastercutdata;
   SCIP_CALL( SCIPhashmapSetImageInt(eventhdlrdata->rowxgeneratedidx, row, eventhdlrdata->ngeneratecuts[sepaidx]) );
   (eventhdlrdata->ngeneratecuts[sepaidx])++;

   return SCIP_OKAY;
}

SCIP_RETCODE addCutToGeneratedCuts(
   SCIP* scip,
   GCG_MASTERCUTDATA* mastercutdata
)
{
   SCIP_EVENTHDLR* eventhdlr;
   SCIP_EVENTHDLRDATA* eventhdlrdata;
   SCIP_ROW* row;
   SCIP_SEPA* sepa;
   int sepaidx;

   assert(scip != NULL);
   assert(GCGisMaster(scip));
   assert(mastercutdata != NULL);

   eventhdlr = SCIPfindEventhdlr(scip, EVENTHDLR_NAME);
   assert(eventhdlr != NULL);

   eventhdlrdata = SCIPeventhdlrGetData(eventhdlr);
   assert(eventhdlrdata != NULL);

   SCIP_CALL( GCGmastercutGetRow(mastercutdata, &row) );
   assert(row != NULL);

   sepa = SCIProwGetOriginSepa(row);
   assert(sepa != NULL);

   sepaidx = SCIPhashmapGetImageInt(eventhdlrdata->sepaxidx, sepa);
   assert(sepaidx != INT_MAX);

   SCIPdebugMessage("Added row %s from separator (%s, %i) to generatedcuts\n", SCIProwGetName(row), SCIPsepaGetName(sepa), sepaidx);
   SCIP_CALL( ensureGeneratedSize(scip, eventhdlrdata, sepaidx, eventhdlrdata->ngeneratecuts[sepaidx] + 1) );
   eventhdlrdata->generatedcuts[sepaidx][eventhdlrdata->ngeneratecuts[sepaidx]] = mastercutdata;
   SCIP_CALL( SCIPhashmapSetImageInt(eventhdlrdata->rowxgeneratedidx, row, eventhdlrdata->ngeneratecuts[sepaidx]) );
   (eventhdlrdata->ngeneratecuts[sepaidx])++;

   return SCIP_OKAY;
}


SCIP_RETCODE clearGeneratedCuts(
   SCIP* scip
   )
{
   SCIP_EVENTHDLR* eventhdlr;
   SCIP_EVENTHDLRDATA* eventhdlrdata;
   SCIP_ROW* row;
   int i;
   int j;

   assert(scip != NULL);
   assert(GCGisMaster(scip));

   eventhdlr = SCIPfindEventhdlr(scip, EVENTHDLR_NAME);
   assert(eventhdlr != NULL);

   eventhdlrdata = SCIPeventhdlrGetData(eventhdlr);
   assert(eventhdlrdata != NULL);

   /* clear out generatedcuts array */
   for( i = 0; i < eventhdlrdata->nsepas; i++ )
   {
      for( j = 0; j < eventhdlrdata->ngeneratecuts[i]; j++ )
      {
         if( eventhdlrdata->generatedcuts[i][j] != NULL  )
         {
            SCIP_CALL( GCGmastercutGetRow(eventhdlrdata->generatedcuts[i][j], &row) );
            assert(row != NULL);

            /* if cut was never in LP: we need to free mastercutdata */
            if( !SCIProwIsInLP(row) )
               SCIP_CALL( GCGmastercutFree(scip, &(eventhdlrdata->generatedcuts[i][j])) );
         }
      }
      eventhdlrdata->ngeneratecuts[i] = 0;
   }

   /* clear corresponding map */
   SCIPhashmapRemoveAll(eventhdlrdata->rowxgeneratedidx);

   return SCIP_OKAY;
}

SCIP_RETCODE GCGremoveNewInactiveRows(
   SCIP* scip,
   int* startidx
   )
{
   SCIP_EVENTHDLR* eventhdlr;
   SCIP_EVENTHDLRDATA* eventhdlrdata;
   SCIP_ROW* row;
   int i;
   int j;

   assert(scip != NULL);
   assert(GCGisMaster(scip));

   eventhdlr = SCIPfindEventhdlr(scip, EVENTHDLR_NAME);
   assert(eventhdlr != NULL);

   eventhdlrdata = SCIPeventhdlrGetData(eventhdlr);
   assert(eventhdlrdata != NULL);

   for( i = 0; i < eventhdlrdata->nsepas; i++ )
   {
      for( j = eventhdlrdata->nactivecuts[i] - 1; j >= startidx[i]; --j )
      {
         SCIP_CALL( GCGmastercutGetRow(eventhdlrdata->activecuts[i][j]->mastercutdata, &row) );
         /* rows still in LP remain relevant */
         if( SCIProwIsInLP(row) )
            continue;

         /* cut was created and removed at focus node: can be permanently removed */
         SCIPdebugMessage("remove new inactive rows: remove row %s and free data\n", SCIProwGetName(row));
         SCIP_CALL( freeStoredCut(scip, &(eventhdlrdata->activecuts[i][j])) );
         assert(eventhdlrdata->activecuts[i][j] == NULL);
         (eventhdlrdata->nactivecuts[i])--;
         eventhdlrdata->activecuts[i][j] = eventhdlrdata->activecuts[i][eventhdlrdata->nactivecuts[i]];
      }
   }
   return SCIP_OKAY;
}

SCIP_RETCODE GCGshrinkActiveCuts(
   SCIP* scip,
   int* newnrows
   )
{
   SCIP_EVENTHDLR* eventhdlr;
   SCIP_EVENTHDLRDATA* eventhdlrdata;
   int i;

   assert(scip != NULL);
   assert(GCGisMaster(scip));

   eventhdlr = SCIPfindEventhdlr(scip, EVENTHDLR_NAME);
   assert(eventhdlr != NULL);

   eventhdlrdata = SCIPeventhdlrGetData(eventhdlr);
   assert(eventhdlrdata != NULL);
   assert(eventhdlrdata->nsepas > 0);

   for( i = 0; i < eventhdlrdata->nsepas; i++ )
   {
      assert(eventhdlrdata->nactivecuts[i] >= newnrows[i]);
      if( eventhdlrdata->nactivecuts[i] == newnrows[i] )
      {
         continue;
      }
      eventhdlrdata->nactivecuts[i] = newnrows[i];
   }

   return SCIP_OKAY;
}

GCG_STOREDCUT*** GCGgetActiveCuts(
   SCIP* scip
   )
{
   SCIP_EVENTHDLR* eventhdlr;
   SCIP_EVENTHDLRDATA* eventhdlrdata;

   assert(scip != NULL);
   assert(GCGisMaster(scip));

   eventhdlr = SCIPfindEventhdlr(scip, EVENTHDLR_NAME);
   assert(eventhdlr != NULL);

   eventhdlrdata = SCIPeventhdlrGetData(eventhdlr);
   assert(eventhdlrdata != NULL);

   return eventhdlrdata->activecuts;
}

int* GCGgetNActiveCuts(
   SCIP* scip
)
{
   SCIP_EVENTHDLR* eventhdlr;
   SCIP_EVENTHDLRDATA* eventhdlrdata;

   assert(scip != NULL);
   assert(GCGisMaster(scip));

   eventhdlr = SCIPfindEventhdlr(scip, EVENTHDLR_NAME);
   assert(eventhdlr != NULL);

   eventhdlrdata = SCIPeventhdlrGetData(eventhdlr);
   assert(eventhdlrdata != NULL);

   return eventhdlrdata->nactivecuts;
}
/*
 * Callback methods of event handler
 */


/** destructor of event handler to free user data (called when SCIP is exiting) */
static
SCIP_DECL_EVENTFREE(eventFreeMastercutUpdate)
{
   SCIP_EVENTHDLRDATA* eventhdlrdata;
   int i;

   assert(scip != NULL);
   assert(eventhdlr != NULL);
   assert(strcmp(SCIPeventhdlrGetName(eventhdlr), EVENTHDLR_NAME) == 0);

   eventhdlrdata = SCIPeventhdlrGetData(eventhdlr);
   assert(eventhdlrdata != NULL);

   SCIPdebugMessage("event free: free hashmaps\n");
   SCIPhashmapFree(&(eventhdlrdata->rowxgeneratedidx));
   SCIPhashmapFree(&(eventhdlrdata->sepaxidx));

   /* free all the arrays */
   if( eventhdlrdata->nsepas > 0)
   {
      SCIPdebugMessage("event free: free mem for (n)activecuts and (n)generatedcuts\n");
      for( i = eventhdlrdata->nsepas - 1; i >= 0 ; i-- )
      {
         SCIPdebugMessage("event free: free mem (%i) for sepa %i\n", eventhdlrdata->activecutssize[i], i);
         SCIPfreeBlockMemoryArray(scip, &(eventhdlrdata->activecuts[i]), eventhdlrdata->activecutssize[i]);
         SCIPfreeBlockMemoryArray(scip, &(eventhdlrdata->generatedcuts[i]), eventhdlrdata->generatecutssize[i]);
      }
      SCIPfreeBlockMemoryArray(scip, &(eventhdlrdata->activecuts), eventhdlrdata->nsepas);
      SCIPfreeBlockMemoryArray(scip, &(eventhdlrdata->generatedcuts), eventhdlrdata->nsepas);
      SCIPfreeBlockMemoryArray(scip, &(eventhdlrdata->nactivecuts), eventhdlrdata->nsepas);
      SCIPfreeBlockMemoryArray(scip, &(eventhdlrdata->ngeneratecuts), eventhdlrdata->nsepas);
      SCIPfreeBlockMemoryArray(scip, &(eventhdlrdata->generatecutssize), eventhdlrdata->nsepas);
      SCIPfreeBlockMemoryArray(scip, &(eventhdlrdata->activecutssize), eventhdlrdata->nsepas);
   }
   else
   {
      SCIPdebugMessage("event free: no sepas registered: arrays remained NULL --> nothing to free\n");
   }
   SCIPdebugMessage("event free: free event handler data\n");
   SCIPfreeBlockMemory(scip, &eventhdlrdata);

   return SCIP_OKAY;
}

/** initialization method of event handler (called after problem was transformed) */
static
SCIP_DECL_EVENTINIT(eventInitMastercutUpdate)
{
   SCIP_EVENTHDLRDATA* eventhdlrdata;
   GCG_SEPA** sepas;
   int initialsize;
   int nsepas;
   int i;

   assert(scip != NULL);
   assert(GCGisMaster(scip));
   assert(eventhdlr != NULL);

   eventhdlrdata = SCIPeventhdlrGetData(eventhdlr);
   assert(eventhdlrdata != NULL);

   /* initialize event handler data:
    * - each separator gets own array of active/all/generated cuts */
   nsepas = GCGrelaxGetNSeparators(scip);
   sepas = GCGrelaxGetSeparators(scip);
   if( nsepas > 0 )
   {
      SCIPdebugMessage("event init: alloc mem for (n)activecuts and (n)generatedcuts\n");
      initialsize = SCIPcalcMemGrowSize(scip, STARTMAXCUTS);
      SCIP_CALL( SCIPallocBlockMemoryArray(scip, &(eventhdlrdata->activecuts), nsepas) );
      SCIP_CALL( SCIPallocBlockMemoryArray(scip, &(eventhdlrdata->generatedcuts), nsepas) );
      SCIP_CALL( SCIPallocBlockMemoryArray(scip, &(eventhdlrdata->nactivecuts), nsepas) );
      SCIP_CALL( SCIPallocBlockMemoryArray(scip, &(eventhdlrdata->ngeneratecuts), nsepas) );
      SCIP_CALL( SCIPallocBlockMemoryArray(scip, &(eventhdlrdata->activecutssize), nsepas) );
      SCIP_CALL( SCIPallocBlockMemoryArray(scip, &(eventhdlrdata->generatecutssize), nsepas) );

      for( i = 0; i < nsepas; i++ )
      {
         SCIPdebugMessage("event init: alloc block mem (%i) for sepa %i\n", initialsize, i);
         SCIP_CALL( SCIPallocBlockMemoryArray(scip, &(eventhdlrdata->activecuts[i]), initialsize) );
         SCIP_CALL( SCIPallocBlockMemoryArray(scip, &(eventhdlrdata->generatedcuts[i]), initialsize) );
         eventhdlrdata->nactivecuts[i] = 0;
         eventhdlrdata->ngeneratecuts[i] = 0;
         eventhdlrdata->generatecutssize[i] = initialsize;
         eventhdlrdata->activecutssize[i] = initialsize;
         SCIP_CALL( SCIPhashmapInsertInt(eventhdlrdata->sepaxidx, sepas[i]->separator, i) );
      }
   }
   else
   {
      SCIPdebugMessage("event init: detected no registered separators --> no need to alloc mem for arrays: set to NULL\n");
      eventhdlrdata->activecuts = NULL;
      eventhdlrdata->generatedcuts = NULL;
      eventhdlrdata->nactivecuts = NULL;
      eventhdlrdata->ngeneratecuts = NULL;
      eventhdlrdata->generatecutssize = NULL;
      eventhdlrdata->activecutssize = NULL;
   }
   SCIPdebugMessage("event init: set nsepas to %i\n", nsepas);
   eventhdlrdata->nsepas = nsepas;
   /* notify SCIP that event handler wants to react on the event types row added to LP and row deleted from LP */
   SCIP_CALL( SCIPcatchEvent(scip, SCIP_EVENTTYPE_ROWADDEDLP, eventhdlr, NULL, NULL) );
   return SCIP_OKAY;
}

/** deinitialization method of event handler (called before transformed problem is freed)
 * - clean up branch-and-bound specific data */
static
SCIP_DECL_EVENTEXITSOL(eventExitSolMastercutUpdate)
{
   SCIP_EVENTHDLRDATA* eventhdlrdata;
   int i;
   int j;

   assert(scip != NULL);
   assert(GCGisMaster(scip));
   assert(eventhdlr != NULL);
   assert(strcmp(SCIPeventhdlrGetName(eventhdlr), EVENTHDLR_NAME) == 0);

   eventhdlrdata = SCIPeventhdlrGetData(eventhdlr);
   assert(eventhdlrdata != NULL);

   /* notify SCIP that your event handler wants to drop the event type lp solved and solution found */
   SCIP_CALL( SCIPdropEvent(scip, SCIP_EVENTTYPE_ROWADDEDLP, eventhdlr, NULL, -1) );

   /* free all the remaining cuts from arrays */
   if( eventhdlrdata->nsepas > 0)
   {
      for( i = eventhdlrdata->nsepas - 1; i >= 0 ; i-- )
      {
         SCIPdebugMessage("event exitsol: free remaining mastercuts in generatedcuts (%i) for sepa %i\n", i,
                          eventhdlrdata->ngeneratecuts[i]);

         for( j = 0; j < eventhdlrdata->ngeneratecuts[i]; j++ )
         {
            assert(eventhdlrdata->generatedcuts[i][j] != NULL);
            SCIP_CALL( GCGmastercutFree(scip, &eventhdlrdata->generatedcuts[i][j]) );
            assert(eventhdlrdata->generatedcuts[i][j] == NULL);
         }
         eventhdlrdata->ngeneratecuts[i] = 0;
         SCIPdebugMessage("event exitsol: free remaining storedcuts (%i) for sepa %i\n", i, eventhdlrdata->nactivecuts[i]);
         for( j = 0; j < eventhdlrdata->nactivecuts[i]; j++ )
         {
            assert(eventhdlrdata->activecuts[i][j] != NULL);
            SCIP_CALL( freeStoredCut(scip, &eventhdlrdata->activecuts[i][j]) );
            assert(eventhdlrdata->activecuts[i][j] == NULL);
         }
         eventhdlrdata->nactivecuts[i] = 0;
      }
   }
   else
   {
      SCIPdebugMessage("event exitsol: no sepas were registered --> array remained NULL\n");
   }
   SCIPdebugMessage("event exitsol: clear hashmaps\n");
   SCIPhashmapRemoveAll(eventhdlrdata->rowxgeneratedidx);
   SCIPhashmapRemoveAll(eventhdlrdata->sepaxidx);

   return SCIP_OKAY;
}

/** main execution method of event handler */
static
SCIP_DECL_EVENTEXEC(eventExecRowAdded)
{
   SCIP_EVENTHDLRDATA* eventhdlrdata;
   GCG_MASTERCUTDATA* mastercutdata;
   GCG_STOREDCUT* storedcut;
   SCIP_ROW* mastercutrow;
   SCIP_ROW* row;
   SCIP_SEPA* sepa;
   int sepaidx;
   int generatedidx;

   assert(scip != NULL);
   assert(GCGisMaster(scip));
   assert(eventhdlr != NULL);
   assert(strcmp(SCIPeventhdlrGetName(eventhdlr), EVENTHDLR_NAME) == 0);
   assert(event != NULL);
   assert(SCIPeventGetType(event) == SCIP_EVENTTYPE_ROWADDEDLP);

   eventhdlrdata = SCIPeventhdlrGetData(eventhdlr);
   assert( eventhdlrdata != NULL );

   /* row is added when LP is already constructed --> row is newly generated cut */
   if( SCIPisLPConstructed(scip) )
   {
      row = SCIPeventGetRow(event);
      sepa = SCIProwGetOriginSepa(row);

      /* if row was not generated by separator: nothing to do */
      if( sepa == NULL )
      {
         SCIPdebugMessage("row added event: cut was not generated by separator\n");
         return SCIP_OKAY;
      }

      sepaidx = SCIPhashmapGetImageInt(eventhdlrdata->sepaxidx, sepa);
      //assert(sepaidx != INT_MAX);
      SCIPdebugMessage("row added event: row %s was generated by sepa (%s, %i)\n", SCIProwGetName(row),
                       SCIPsepaGetName(sepa), sepaidx);
      if( SCIPhashmapExists(eventhdlrdata->rowxgeneratedidx, row) )
      {
         /* create corresponding storedcut of new row and add it to active cuts */
         SCIPdebugMessage("row added event: row %s is added to active cuts at %i\n", SCIProwGetName(row),
                          eventhdlrdata->nactivecuts[sepaidx]);
         generatedidx = SCIPhashmapGetImageInt(eventhdlrdata->rowxgeneratedidx, row);
         mastercutdata = eventhdlrdata->generatedcuts[sepaidx][generatedidx];
         SCIP_CALL( GCGmastercutGetRow(mastercutdata, &mastercutrow) );
         assert(mastercutrow == row);
         SCIP_CALL( ensureActiveSize(scip, eventhdlrdata, sepaidx, eventhdlrdata->nactivecuts[sepaidx] + 1) );
         SCIP_CALL( createStoredCut(scip, &storedcut, mastercutdata) );
         eventhdlrdata->activecuts[sepaidx][eventhdlrdata->nactivecuts[sepaidx]] = storedcut;
         (eventhdlrdata->nactivecuts[sepaidx])++;
      }
   }

   return SCIP_OKAY;
}

SCIP_RETCODE GCGaddCutTActiveCuts(
   SCIP* scip,
   GCG_STOREDCUT* storedcut,
   int sepaidx
   )
{
   SCIP_EVENTHDLR* eventhdlr;
   SCIP_EVENTHDLRDATA* eventhdlrdata;

   assert(scip != NULL);
   assert(GCGisMaster(scip));

   eventhdlr = SCIPfindEventhdlr(scip, EVENTHDLR_NAME);
   assert(eventhdlr != NULL);

   eventhdlrdata = SCIPeventhdlrGetData(eventhdlr);
   assert(eventhdlrdata != NULL);

   SCIP_CALL( ensureActiveSize(scip, eventhdlrdata, sepaidx, eventhdlrdata->nactivecuts[sepaidx] + 1) );
   eventhdlrdata->activecuts[sepaidx][eventhdlrdata->nactivecuts[sepaidx]] = storedcut;
   (eventhdlrdata->nactivecuts[sepaidx])++;

   return SCIP_OKAY;
}


/** creates event handler for xyz event */
SCIP_RETCODE SCIPincludeEventHdlrSepaCuts(
   SCIP*                 scip                /**< SCIP data structure */
   )
{
   SCIP_EVENTHDLRDATA* eventhdlrdata;
   SCIP_EVENTHDLR* eventhdlr;

   /* create event handler data */
   SCIPdebugMessage("include: alloc mem for eventhandler data\n");
   SCIP_CALL( SCIPallocBlockMemory(scip, &eventhdlrdata) );
   assert(eventhdlrdata != NULL);
   SCIPdebugMessage("include: create hashmaps and set nsepas to 0\n");
   SCIP_CALL( SCIPhashmapCreate(&(eventhdlrdata->rowxgeneratedidx), SCIPblkmem(scip), STARTMAXCUTS) );
   SCIP_CALL( SCIPhashmapCreate(&(eventhdlrdata->sepaxidx), SCIPblkmem(scip), 10) );
   eventhdlrdata->nsepas = 0;
   /* use SCIPincludeEventhdlrBasic() plus setter functions if you want to set callbacks one-by-one and your code should
    * compile independent of new callbacks being added in future SCIP versions
    */
   eventhdlr = NULL;
   SCIP_CALL( SCIPincludeEventhdlrBasic(scip, &eventhdlr, EVENTHDLR_NAME, EVENTHDLR_DESC,
         eventExecRowAdded, eventhdlrdata) );
   assert(eventhdlr != NULL);

   /* set non fundamental callbacks via setter functions */
   SCIP_CALL( SCIPsetEventhdlrInit(scip, eventhdlr, eventInitMastercutUpdate) );
   SCIP_CALL( SCIPsetEventhdlrExitsol(scip, eventhdlr, eventExitSolMastercutUpdate) );
   SCIP_CALL( SCIPsetEventhdlrFree(scip, eventhdlr, eventFreeMastercutUpdate) );

   return SCIP_OKAY;
}
