/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/*                                                                           */
/*                  This file is part of the program                         */
/*          GCG --- Generic Column Generation                                */
/*                  a Dantzig-Wolfe decomposition based extension            */
/*                  of the branch-cut-and-price framework                    */
/*         SCIP --- Solving Constraint Integer Programs                      */
/*                                                                           */
/* Copyright (C) 2010-2024 Operations Research, RWTH Aachen University       */
/*                         Zuse Institute Berlin (ZIB)                       */
/*                                                                           */
/* This program is free software; you can redistribute it and/or             */
/* modify it under the terms of the GNU Lesser General Public License        */
/* as published by the Free Software Foundation; either version 3            */
/* of the License, or (at your option) any later version.                    */
/*                                                                           */
/* This program is distributed in the hope that it will be useful,           */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of            */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             */
/* GNU Lesser General Public License for more details.                       */
/*                                                                           */
/* You should have received a copy of the GNU Lesser General Public License  */
/* along with this program; if not, write to the Free Software               */
/* Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.*/
/*                                                                           */
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/**@file   struct_mastersepacutdata.h
 * @ingroup DATASTRUCTURES
 * @brief  data structures for GCG separator cut data
 * @author Chantal Reinartz Groba
 */

/*---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9----+----0----+----1----+----2*/

#ifndef GCG_STRUCT_MASTERSEPACUTDATA_H__
#define GCG_STRUCT_MASTERSEPACUTDATA_H__

#include <scip/def.h>
#include "mastercutdata.h"
#include "type_varhistory.h"
#include "type_sepagcg.h"

#ifdef __cplusplus
extern "C" {
#endif

/** type of the master separator cut */
enum GCG_MasterSepaCutType
{
   GCG_MASTERSEPACUTTYPE_SUBSETROW = 0                /**< cut was generated by subset row separator */
};
typedef enum GCG_MasterSepaCutType GCG_MASTERSEPACUTTYPE;

/** additional data for subset row cuts */
struct GCG_SubsetRowCutData
{
   int                     n;                      /**< number of constraints used to create cut */
   int*                    conssindices;           /**< indices of constraints used to create cut */
   SCIP_Real*              weights;                /**< weights used to create cut */
};
typedef struct GCG_SubsetRowCutData GCG_SUBSETROWCUTDATA;

struct GCG_MasterSepaCutData
{
   union
   {
      GCG_SUBSETROWCUTDATA    subsetrowcutdata;       /**< data for subset row cuts */
   } data;
};
typedef struct GCG_MasterSepaCutData GCG_MASTERSEPACUTDATA;

/** variable data structure */
struct GCG_MasterSepaCut
{
   GCG_MASTERSEPACUTDATA*     data;
   int                        sepaidx;                /**< index of separator which created cut */
   GCG_MASTERSEPACUTTYPE      cuttype;                /**< type of cut */
   GCG_MASTERCUTDATA*         mastercutdata;          /**< master cut data */
   GCG_VARHISTORY*            knownvarhistory;        /**< pointer to the history of priced variables */
   int                        nuses;                  /**< number of times this cut is referenced */
};
typedef struct GCG_MasterSepaCut GCG_MASTERSEPACUT;

#ifdef __cplusplus
}
#endif

#endif