/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/*                                                                           */
/*                  This file is part of the program                         */
/*          GCG --- Generic Column Generation                                */
/*                  a Dantzig-Wolfe decomposition based extension            */
/*                  of the branch-cut-and-price framework                    */
/*         SCIP --- Solving Constraint Integer Programs                      */
/*                                                                           */
/* Copyright (C) 2010-2024 Operations Research, RWTH Aachen University       */
/*                         Zuse Institute Berlin (ZIB)                       */
/*                                                                           */
/* This program is free software; you can redistribute it and/or             */
/* modify it under the terms of the GNU Lesser General Public License        */
/* as published by the Free Software Foundation; either version 3            */
/* of the License, or (at your option) any later version.                    */
/*                                                                           */
/* This program is distributed in the hope that it will be useful,           */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of            */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             */
/* GNU Lesser General Public License for more details.                       */
/*                                                                           */
/* You should have received a copy of the GNU Lesser General Public License  */
/* along with this program; if not, write to the Free Software               */
/* Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.*/
/*                                                                           */
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/**@file    type_mastersepacut.h
 * @ingroup TYPEDEFINITIONS
 * @brief   type definitions for master separator cuts
 * @author  Chantal Reinartz Groba
 */

/*---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9----+----0----+----1----+----2*/


#ifndef GCG_TEST_MASTERSEPACUT_H__
#define GCG_TEST_MASTERSEPACUT_H__


#ifdef __cplusplus
extern "C" {
#endif

/** type of the master separator cut */
enum GCG_MasterSepaCutType
{
   GCG_MASTERSEPACUTTYPE_SUBSETROW = 0                /**< cut was generated by subset row separator */
};
typedef enum GCG_MasterSepaCutType GCG_MASTERSEPACUTTYPE;

typedef struct GCG_SubsetRowCutData GCG_SUBSETROWCUTDATA;
typedef struct GCG_MasterSepaCutData GCG_MASTERSEPACUTDATA;
typedef struct GCG_MasterSepaCut GCG_MASTERSEPACUT;

#ifdef __cplusplus
}
#endif

#endif
