<div id="authors">
  <h2><a name="main"></a>Current team</h2>
  <h3>Project head</h3>
  <table class="desc">
    <tr>
      <td width="180px">
    <a href="http://www.or.rwth-aachen.de/luebbecke">Marco Lübbecke</a>
      </td>
      <td>
    Project initiator and head
      </td>
    </tr>
  </table>
  <br />
  <h3>Main developers</h3>
  <table class="desc">
    <tr>
      <td width="180px">
        <a href="http://www.or.rwth-aachen.de/team/staff/michael-bastubbe/">Michael Bastubbe</a>
      </td>
      <td>
    Structure detection
      </td>
    </tr>
    <tr>
      <td width="180px">
    <a href="http://www.or.rwth-aachen.de/bergner">Martin Bergner</a>
      </td>
      <td>
    Structure detection, former main developer
      </td>
    </tr>
    <tr>
      <td>
    <a href="http://www.zib.de/gamrath/">Gerald Gamrath</a>
      </td>
      <td>
    Original and main developer
      </td>
    </tr>
    <tr>
      <td>
    <a href="http://www.or.rwth-aachen.de/puchert/">Christian Puchert</a>
      </td>
      <td>
        Primal heuristics, main developer
      </td>
    </tr>
    <tr>
      <td>
    <a href="http://www.or.rwth-aachen.de/team/staff/jonas-witt/">Jonas Witt</a>
      </td>
      <td>
        Cutting planes, main developer
      </td>
    </tr>
  </table>
  <br />
  <h3>Contributors</h3>
  <table class="desc">
    <tr>
      <td width="180px">
    Björn Dählmann
      </td>
      <td>
    Student assistant, structure detection
      </td>
    </tr>
    <tr>
      <td width="180px">
    Hanna Franzen
      </td>
      <td>
    Student assistant, structure detection
      </td>
    </tr>
    <tr>
      <td>
    Alexander Groß
      </td>
      <td>
    Student assistant, statistics
      </td>
    </tr>
    <tr>
      <td width="180px">
    Lukas Kirchhart
      </td>
      <td>
    Student assistant, documentation
      </td>
    </tr>
    <tr>
      <td width="180px">
    Tobias Oelschlägel
      </td>
      <td>
    Student assistant, set covering heuristic
      </td>
    </tr>
    <tr>
      <td width="180px">
    Marc Peiter
      </td>
      <td>
    Student assistant, testing
      </td>
    </tr>
    <tr>
      <td width="180px">
    Daniel Peters
      </td>
      <td>
    Student assistant, detection of similar pricing problems
      </td>
    </tr>
    <tr>
      <td width="180px">
    Marcel Schmickerath
      </td>
      <td>
    Student assistant, generic branching
      </td>
    </tr>
    <tr>
      <td width="180px">
        <a href="http://www.or.rwth-aachen.de/team/staff/annika-thome/">Annika Thome</a>
      </td>
      <td>
    Graph library methods
      </td>
    </tr>
  </table>
</div>

