<div id="authors">
             
    <h2><a name="main"></a>Current main developers</h2>

        <table class="desc">
	    <tr>
	      <td width="180px">
		<a href="http://www.zib.de/gamrath/">Gerald Gamrath</a>
	      </td>
	      <td>
		…
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.or.rwth-aachen.de/people/puchert/">Christian Puchert</a>
	      </td>
	      <td>
                Primal heuristics
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.or.rwth-aachen.de/people/bergner">Martin Bergner</a>
	      </td>
	      <td> Solution counting, global constraints
	      </td>
	    </tr>
	</table>
</div>

